/** Declaration file generated by dts-gen */

export = airtable;

declare class airtable {
    constructor(...args: any[]);

    base(baseId: any): any;

    init(opts: any): void;

    static base(baseId: any): any;

    static configure(opts: any): void;

    static default_config(): any;

    static extend(prop: any, ...args: any[]): any;

}

declare namespace airtable {
    class Base {
        constructor(...args: any[]);

        doCall(tableName: any): any;

        getId(): any;

        init(airtable: any, baseId: any): void;

        runAction(method: any, path: any, queryParams: any, bodyData: any, callback: any): void;

        table(tableName: any): any;

    }

    class Error {
        constructor(...args: any[]);

        init(error: any, message: any, statusCode: any): void;

        toString(): any;

    }

    class Record {
        constructor(...args: any[]);

        destroy(done: any): void;

        fetch(done: any): void;

        get(columnName: any): any;

        getId(): any;

        init(table: any, recordId: any, recordJson: any): void;

        patchUpdate(cellValuesByName: any, opts: any, done: any): void;

        putUpdate(cellValuesByName: any, opts: any, done: any): void;

        save(done: any): void;

        set(columnName: any, columnValue: any): void;

        setRawJson(rawJson: any): void;

    }

    class Table {
        constructor(...args: any[]);

        init(base: any, tableId: any, tableName: any): void;

    }

    namespace Base {
        namespace createFunctor {
            const prototype: {
            };

        }

        namespace extend {
            const prototype: {
            };

        }

    }

    namespace Error {
        namespace extend {
            const prototype: {
            };

        }

    }

    namespace Record {
        namespace extend {
            const prototype: {
            };

        }

    }

    namespace Table {
        namespace extend {
            const prototype: {
            };

        }

    }

}

